global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'risk_engine'
    static_configs:
      - targets: ['risk_engine:8002']

  - job_name: 'personalizer'
    static_configs:
      - targets: ['personalizer:8003']
