from typing import List
import re


INTERACTION_KEYWORDS = [
    "retinyl propionate",
    "retinyl palmitate",
    "retinyl acetate",
    "retinaldehyde",
    "l-ascorbic acid",
    "capryloyl salicylic acid",
    "beta hydroxy acid",
    "lipo hydroxy acid",
    "alpha hydroxy acid",
    "polyhydroxy acid",
    "sodium ascorbyl phosphate",
    "magnesium ascorbyl phosphate",
    "tetrahexyldecyl ascorbate",
    "ethyl ascorbic acid",
    "ascorbyl glucoside",
    "benzoyl peroxide",
    "hydrogen peroxide",
    "salicylic acid",
    "glycolic acid",
    "lactic acid",
    "mandelic acid",
    "azelaic acid",
    "tranexamic acid",
    "kojic acid",
    "alpha arbutin",
    "ammonium lactate",
    "sodium lactate",
    "benzalkonium chloride",
    "isopropyl alcohol",
    "denatured alcohol",
    "alcohol denat",
    "octyl methoxycinnamate",
    "cocamidopropyl betaine",
    "sodium lauryl sulfate",
    "sodium laureth sulfate",
    "methylchloroisothiazolinone",
    "methylisothiazolinone",
    "benzisothiazolinone",
    "quaternium-15",
    "dmdm hydantoin",
    "imidazolidinyl urea",
    "diazolidinyl urea",
    "methyldibromo glutaronitrile",
    "balsam of peru",
    "hexyl cinnamal",
    "lavender oil",
    "peppermint oil",
    "eucalyptus oil",
    "tea tree oil",
    "retinol",
    "retinal",
    "tretinoin",
    "isotretinoin",
    "adapalene",
    "tazarotene",
    "trifarotene",
    "bakuchiol",
    "bha",
    "lha",
    "aha",
    "pha",
    "gluconolactone",
    "lactobionic acid",
    "citric acid",
    "malic acid",
    "tartaric acid",
    "resorcinol",
    "sulfur",
    "sulphur",
    "urea",
    "ascorbic acid",
    "vitamin c",
    "hydroquinone",
    "arbutin",
    "cysteamine",
    "thiamidol",
    "methimazole",
    "witch hazel",
    "ethanol",
    "chlorhexidine",
    "povidone iodine",
    "avobenzone",
    "homosalate",
    "octisalate",
    "octocrylene",
    "oxybenzone",
    "benzophenone-3",
    "benzophenone",
    "ensulizole",
    "octinoxate",
    "ecamsule",
    "meradimate",
    "padimate o",
    "dioxybenzone",
    "sulisobenzone",
    "bemotrizinol",
    "bisoctrizole",
    "cinnamate",
    "fragrance",
    "parfum",
    "perfume",
    "essential oil",
    "limonene",
    "linalool",
    "citral",
    "citronellol",
    "eugenol",
    "geraniol",
    "farnesol",
    "coumarin",
    "cinnamal",
    "menthol",
    "camphor",
    "formaldehyde",
    "phenoxyethanol",
    "sulfacetamide",
    "clindamycin",
    "erythromycin",
    "dapsone",
    "benzocaine",
    "acrylates",
    "propylene glycol",
    "lanolin",
]


def extract_interaction_relevant_ingredients(ingredients_text: str | None) -> List[str]:
    if not ingredients_text:
        return []

    text_lower = ingredients_text.lower()
    found = []

    for keyword in INTERACTION_KEYWORDS:
        pattern = r"(?<![a-z0-9])" + re.escape(keyword.lower()) + r"(?![a-z0-9])"
        if re.search(pattern, text_lower):
            found.append(keyword)

    found = list(dict.fromkeys(found))

    if "alpha arbutin" in found and "arbutin" in found:
        found.remove("arbutin")

    return found